spring :
  datasource:
    url : jdbc:h2:tcp://localhost/~/vueTest
    username : sa
    password : 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug