spring :
  datasource:
#    url : jdbc:h2:tcp://localhost/~/vueTest
    url : jdbc:h2:mem:testdb
    username : sa
#    password : 1
    password :
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL : debug